import Head from "next/head";
import { useStyles } from "../styles/Home.style.js";
import TabsWrapper from "../Components/TabsWrapper/TabsWrapper";

export default function Home() {
  const styles = useStyles();
  return (
    <div className={styles.root}>
      <Head>
        <title>Tabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TabsWrapper />
      </main>
    </div>
  );
}
